/**
 * Component Registry
 *
 * Single source of truth for every component in the gallery.
 * Powers: homepage grid, sidebar nav, search, related components,
 * breadcrumbs, component counts, and future filters.
 *
 * status:
 *   'complete'     — gallery page exists and is fully built
 *   'wip'          — page exists but is incomplete
 *   'coming-soon'  — planned, no page yet
 */

export type ComponentStatus = 'complete' | 'wip' | 'coming-soon';

export interface ComponentEntry {
  id: string;
  name: string;
  category: string;
  status: ComponentStatus;
  /** null = no route yet (coming soon) */
  route: string | null;
  aliases: string[];
  description: string;
  popular?: boolean;
}

export const GALLERY_CATEGORIES = [
  'Foundations',
  'Inputs',
  'Display',
  'Navigation',
  'Overlay',
  'Layout',
  'Data Display',
  'Enterprise',
] as const;

export type GalleryCategory = typeof GALLERY_CATEGORIES[number];

export const COMPONENT_REGISTRY: ComponentEntry[] = [
  // ── Foundations ────────────────────────────────────────────────────────
  {
    id: 'brand-strategy',
    name: 'Brand Strategy',
    category: 'Foundations',
    status: 'complete',
    route: '/ui-library/brand-strategy',
    aliases: ['brand roots', 'vision', 'mission', 'values', 'brand promise', 'quality policy', 'company overview'],
    description: 'Company overview, vision, mission, corporate values, quality policy, and brand promise.',
  },
  {
    id: 'brand-narrative',
    name: 'Brand Narrative',
    category: 'Foundations',
    status: 'complete',
    route: '/ui-library/brand-narrative',
    aliases: ['brand expression', 'character', 'persona', 'look and feel', 'creative evolution', 'brand identity'],
    description: 'How the brand expresses itself — Character & Persona, Tone & Manner, Look & Feel, and the Creative Evolution checklist.',
  },
  {
    id: 'voice-tone',
    name: 'Voice & Tone',
    category: 'Foundations',
    status: 'complete',
    route: '/ui-library/voice-tone',
    aliases: ['voice', 'tone', 'writing principles', 'communication', 'messaging', 'copy guidelines'],
    description: 'Writing principles for UI copy — conviction, empowerment, professionalism, and simplicity.',
  },
  {
    id: 'writing-examples',
    name: 'Writing Examples',
    category: 'Foundations',
    status: 'complete',
    route: '/ui-library/writing-examples',
    aliases: ['copy examples', 'ux writing', 'ui copy', 'writing samples', 'do dont writing'],
    description: 'Do/don\'t examples for button labels, page headers, empty states, errors, confirmations, and form labels.',
  },
  {
    id: 'responsive',
    name: 'Responsive',
    category: 'Foundations',
    status: 'complete',
    route: '/ui-library/responsive',
    aliases: ['breakpoint', 'mobile', 'tablet', 'responsive design', 'media query', 'sm md lg xl', 'touch target'],
    description: 'Breakpoint scale, layout shift rules, touch targets, and a machine-readable rules reference for every screen size.',
  },
  {
    id: 'installation',
    name: 'Installation',
    category: 'Foundations',
    status: 'complete',
    route: '/ui-library/installation',
    aliases: ['install', 'setup', 'npm', 'getting started', 'package'],
    description: 'How to install the package, set up fonts, configure Tailwind, and register the Toaster.',
  },
  {
    id: 'logo',
    name: 'Logo',
    category: 'Foundations',
    status: 'complete',
    route: '/ui-library/logo',
    aliases: ['brand', 'logomark', 'wordmark', 'identity'],
    description: 'Logo lockups, color variants, clear space rules, minimum sizes, and misuse examples.',
  },
  {
    id: 'colors',
    name: 'Colors',
    category: 'Foundations',
    status: 'complete',
    route: '/ui-library/colors',
    aliases: ['color', 'palette', 'tokens'],
    description: 'The full color system — brand blues, semantic status colors, and neutrals with usage rules.',
  },
  {
    id: 'typography',
    name: 'Typography',
    category: 'Foundations',
    status: 'complete',
    route: '/ui-library/typography',
    aliases: ['font', 'text', 'type'],
    description: 'Two typefaces, a type scale, and the rules for when to use each level.',
  },
  {
    id: 'spacing',
    name: 'Spacing',
    category: 'Foundations',
    status: 'complete',
    route: '/ui-library/spacing',
    aliases: ['space', 'gap', 'padding', 'margin'],
    description: 'Spacing conventions built on the Tailwind default scale — which values to use and where.',
  },
  {
    id: 'radius',
    name: 'Radius',
    category: 'Foundations',
    status: 'complete',
    route: '/ui-library/radius',
    aliases: ['border-radius', 'rounded', 'corners'],
    description: 'Border radius values mapped to component types. rounded-xl is the standard card radius.',
  },
  {
    id: 'elevation',
    name: 'Elevation',
    category: 'Foundations',
    status: 'complete',
    route: '/ui-library/elevation',
    aliases: ['shadow', 'depth', 'z-index'],
    description: 'Box shadow and z-index scale — how depth is expressed across cards, modals, and dropdowns.',
  },
  {
    id: 'motion',
    name: 'Motion',
    category: 'Foundations',
    status: 'complete',
    route: '/ui-library/motion',
    aliases: ['animation', 'transition', 'easing'],
    description: 'Reusable CSS animation classes. Apply a class name and the motion handles itself.',
  },
  {
    id: 'icons',
    name: 'Icons',
    category: 'Foundations',
    status: 'complete',
    route: '/ui-library/icons',
    aliases: ['icon', 'lucide', 'svg'],
    description: 'Searchable icon library from lucide-react. All icons are bundled — no separate install needed.',
  },

  // ── Inputs ─────────────────────────────────────────────────────────────
  {
    id: 'button',
    name: 'Button',
    category: 'Inputs',
    status: 'complete',
    route: '/ui-library/button',
    aliases: ['btn', 'cta', 'action'],
    description: 'Clickable action trigger. Five variants: primary, dark, outline, ghost, danger. Supports loading state.',
    popular: true,
  },
  {
    id: 'icon-button',
    name: 'Icon Button',
    category: 'Inputs',
    status: 'complete',
    route: '/ui-library/icon-button',
    aliases: ['iconbtn', 'icon btn', 'square button'],
    description: 'Square button that holds a single icon. Always requires an aria-label. Three variants: default, edit, danger.',
  },
  {
    id: 'input',
    name: 'Input',
    category: 'Inputs',
    status: 'complete',
    route: '/ui-library/input',
    aliases: ['text input', 'text field', 'textbox'],
    description: 'Single-line text input with prefix/suffix icon slots, validation states, and helper text.',
    popular: true,
  },
  {
    id: 'textarea',
    name: 'Textarea',
    category: 'Inputs',
    status: 'complete',
    route: '/ui-library/textarea',
    aliases: ['multiline', 'text area'],
    description: 'Multi-line text input with character count, validation states, and configurable resize.',
  },
  {
    id: 'field',
    name: 'Field',
    category: 'Inputs',
    status: 'complete',
    route: '/ui-library/field',
    aliases: ['form field', 'field wrapper', 'label'],
    description: 'Form field wrapper that wires label, error, and helper text to any input via context.',
    popular: true,
  },
  {
    id: 'field-input',
    name: 'FieldInput',
    category: 'Inputs',
    status: 'complete',
    route: '/ui-library/field-input',
    aliases: ['context input', 'field input', 'auto aria input'],
    description: 'Input that reads its id and ARIA attributes from a parent Field — no extra props needed.',
  },
  {
    id: 'segmented-control',
    name: 'Segmented Control',
    category: 'Inputs',
    status: 'complete',
    route: '/ui-library/segmented-control',
    aliases: ['segmented', 'inline toggle', 'pill toggle'],
    description: 'Inline toggle strip for switching between a small set of mutually exclusive options.',
  },
  {
    id: 'checkbox',
    name: 'Checkbox',
    category: 'Inputs',
    status: 'complete',
    route: '/ui-library/checkbox',
    aliases: ['check', 'tick'],
    description: 'Binary or indeterminate selection control with optional label and description. Supports error state.',
  },
  {
    id: 'radio',
    name: 'Radio',
    category: 'Inputs',
    status: 'complete',
    route: '/ui-library/radio-group',
    aliases: ['radio button', 'radio group'],
    description: 'Group of radio buttons for selecting one option from a list. Keyboard navigable out of the box.',
  },
  {
    id: 'switch',
    name: 'Switch',
    category: 'Inputs',
    status: 'complete',
    route: '/ui-library/switch',
    aliases: ['toggle', 'on off'],
    description: 'On/off toggle for settings that take effect immediately — not for form submissions.',
  },
  {
    id: 'select',
    name: 'Select',
    category: 'Inputs',
    status: 'complete',
    route: '/ui-library/select',
    aliases: ['dropdown select', 'single select'],
    description: 'Native single-value dropdown. Fully accessible. Use Combobox for search or multi-select.',
    popular: true,
  },
  {
    id: 'combobox',
    name: 'Combobox',
    category: 'Inputs',
    status: 'complete',
    route: '/ui-library/combobox',
    aliases: ['autocomplete', 'searchable select', 'typeahead'],
    description: 'Text input with a filtered suggestion dropdown. User can type a value not in the list.',
  },
  {
    id: 'date-picker',
    name: 'Date Picker',
    category: 'Inputs',
    status: 'complete',
    route: '/ui-library/date-picker',
    aliases: ['datepicker', 'calendar input', 'date field'],
    description: 'Calendar popup that returns a yyyy-MM-dd string. Flips above or below the trigger based on viewport space.',
  },
  {
    id: 'file-upload',
    name: 'File Upload',
    category: 'Inputs',
    status: 'complete',
    route: '/ui-library/file-upload',
    aliases: ['file input', 'upload', 'dropzone'],
    description: 'Drag-and-drop zone over a native file input. Shows the selected file list. HTTP upload is handled by you.',
  },
  {
    id: 'otp-input',
    name: 'OTP Input',
    category: 'Inputs',
    status: 'complete',
    route: '/ui-library/otp-input',
    aliases: ['otp', 'pin input', 'verification code'],
    description: 'Segmented digit boxes for one-time passwords and PINs. Auto-advances, handles paste, backspace navigates.',
  },
  {
    id: 'filter-chip',
    name: 'FilterChip',
    category: 'Inputs',
    status: 'complete',
    route: '/ui-library/filter-chip',
    aliases: ['chip', 'tag', 'removable tag', 'active filter', 'filter tag'],
    description: 'Removable tag that represents an active filter. Click the × to remove it.',
  },
  {
    id: 'search',
    name: 'Search',
    category: 'Inputs',
    status: 'complete',
    route: '/ui-library/search',
    aliases: ['search input', 'search bar', 'search field', 'filter input', 'find'],
    description: 'Search input with built-in icon and optional clear button. Use for filtering tables, lists, and discovery flows.',
  },

  // ── Display ────────────────────────────────────────────────────────────
  {
    id: 'card',
    name: 'Card',
    category: 'Display',
    status: 'complete',
    route: '/ui-library/card',
    aliases: ['panel', 'surface'],
    description: 'White surface for grouping related content. Slots for header, content, and footer.',
    popular: true,
  },
  {
    id: 'badge',
    name: 'Badge',
    category: 'Display',
    status: 'complete',
    route: '/ui-library/badge',
    aliases: ['chip', 'tag', 'label', 'pill'],
    description: 'Small label for categories and metadata. Eight tones, two sizes, optional icon.',
    popular: true,
  },
  {
    id: 'avatar',
    name: 'Avatar',
    category: 'Display',
    status: 'complete',
    route: '/ui-library/avatar',
    aliases: ['profile picture', 'user icon', 'initials'],
    description: 'Circular user tile. Shows a photo if available, falls back to initials.',
  },
  {
    id: 'status-dot',
    name: 'Status Dot',
    category: 'Display',
    status: 'complete',
    route: '/ui-library/status-dot',
    aliases: ['dot indicator', 'status indicator', 'colored dot', 'masked value', 'redacted', 'sensitive value', 'hidden value', 'restricted value'],
    description: 'Inline display primitives. StatusDot: coloured glowing dot for entity status (active, inactive, locked, pending). MaskedValue: shows a real value or a redacted placeholder based on a boolean condition — useful for permission-gated data.',
  },
  {
    id: 'alert',
    name: 'Alert',
    category: 'Display',
    status: 'complete',
    route: '/ui-library/alert',
    aliases: ['banner', 'notification', 'callout'],
    description: 'Inline contextual message. Four tones: info, success, warning, danger. Stays on the page.',
  },
  {
    id: 'toast',
    name: 'Toast',
    category: 'Display',
    status: 'complete',
    route: '/ui-library/toast',
    aliases: ['notification', 'snackbar', 'sonner', 'toaster'],
    description: 'Temporary notification that appears in the corner and auto-dismisses. Call toast() anywhere.',
    popular: true,
  },
  {
    id: 'spinner',
    name: 'Spinner',
    category: 'Display',
    status: 'complete',
    route: '/ui-library/spinner',
    aliases: ['loader', 'loading', 'progress circular'],
    description: 'Circular loading indicator for indeterminate wait states. Three sizes.',
  },
  {
    id: 'skeleton',
    name: 'Skeleton',
    category: 'Display',
    status: 'complete',
    route: '/ui-library/skeleton',
    aliases: ['skeleton loader', 'placeholder', 'shimmer'],
    description: 'Animated placeholder shapes shown while content loads. Prevents layout shift.',
  },
  {
    id: 'empty-state',
    name: 'Empty State',
    category: 'Display',
    status: 'complete',
    route: '/ui-library/empty-state',
    aliases: ['empty', 'no data', 'zero state'],
    description: 'Illustration, heading, and optional CTA for when a list has no items to show.',
  },
  {
    id: 'status-page',
    name: 'StatusPage',
    category: 'Display',
    status: 'complete',
    route: '/ui-library/status-page',
    aliases: ['404', '403', '500', 'error page', 'not found', 'forbidden', 'server error', 'maintenance', 'status page', 'full page error'],
    description: 'Full-page status screen for 404, 403, 500, and custom states. Typographic code watermark, eyebrow label, heading, description, and action buttons. No routing logic — consumer wires navigation.',
  },
  {
    id: 'not-found-error',
    name: 'NotFoundError',
    category: 'Display',
    status: 'complete',
    route: '/ui-library/not-found-error',
    aliases: ['404', 'not found', 'page not found', 'missing page', 'error page', 'catch all route'],
    description: 'Full-page 404 Not Found screen. Composes StatusPage with the notFound preset. Consumer wires navigation via primaryAction and secondaryAction callbacks.',
  },
  {
    id: 'forbidden-error',
    name: 'ForbiddenError',
    category: 'Display',
    status: 'complete',
    route: '/ui-library/forbidden-error',
    aliases: ['403', 'forbidden', 'access denied', 'access restricted', 'no permission', 'unauthorized', 'error page'],
    description: 'Full-page 403 Access Restricted screen. Composes StatusPage with the forbidden preset. Consumer wires navigation via callbacks.',
  },
  {
    id: 'application-error',
    name: 'ApplicationError',
    category: 'Display',
    status: 'complete',
    route: '/ui-library/application-error',
    aliases: ['500', 'server error', 'something went wrong', 'error boundary', 'crash', 'runtime error', 'unexpected error', 'ApplicationErrorFallback'],
    description: 'Full-page 500 error screen for unexpected runtime failures. Dev-only collapsible details panel (stack trace, component stack). Two exports: ApplicationError and ApplicationErrorFallback for ErrorBoundary use.',
  },
  {
    id: 'statistic',
    name: 'Statistic',
    category: 'Display',
    status: 'complete',
    route: '/ui-library/statistic',
    aliases: ['stat', 'kpi', 'metric', 'number', 'kpi card', 'stat card', 'stat-card'],
    description: 'KPI tile showing a number, label, trend arrow, and icon. Four variants: default, accent, minimal, compact.',
  },
  {
    id: 'description-list',
    name: 'Description List',
    category: 'Display',
    status: 'complete',
    route: '/ui-library/description-list',
    aliases: ['dl', 'key value', 'detail list', 'label value', 'read-only field'],
    description: 'Label/value pairs for read-only detail views. Horizontal and vertical layouts.',
  },
  {
    id: 'status-badge',
    name: 'StatusBadge',
    category: 'Display',
    status: 'complete',
    route: '/ui-library/status-badge',
    aliases: ['status badge', 'state badge', 'entity status', 'status pill'],
    description: 'Semantic status pill. Six tones: neutral, success, warning, error, info, primary. Use when color carries meaning.',
  },
  {
    id: 'timeline',
    name: 'Timeline',
    category: 'Display',
    status: 'complete',
    route: '/ui-library/timeline',
    aliases: ['activity', 'history', 'log', 'audit trail', 'change history'],
    description: 'Vertical list of chronological events with timestamps, actors, and optional before/after values.',
  },
  {
    id: 'progress',
    name: 'Progress',
    category: 'Display',
    status: 'complete',
    route: '/ui-library/progress',
    aliases: ['progress bar', 'loading bar', 'completion', 'upload progress'],
    description: 'Horizontal progress bar. Supports 0–100% determinate and animated indeterminate modes.',
  },
  {
    id: 'error-banner',
    name: 'ErrorBanner',
    category: 'Display',
    status: 'complete',
    route: '/ui-library/error-banner',
    aliases: ['error', 'banner', 'feedback', 'inline error', 'warning banner'],
    description: 'Dismissible banner for form-level or section-level error and warning feedback.',
  },
  {
    id: 'validation-summary',
    name: 'ValidationSummary',
    category: 'Display',
    status: 'complete',
    route: '/ui-library/validation-summary',
    aliases: ['validation', 'form errors', 'field errors', 'validation errors', 'form summary'],
    description: 'Grouped list of validation errors above a form. Renders nothing when the list is empty.',
  },

  // ── Navigation ─────────────────────────────────────────────────────────
  {
    id: 'tabs',
    name: 'Tabs',
    category: 'Navigation',
    status: 'complete',
    route: '/ui-library/tabs',
    aliases: ['tab', 'segmented control', 'tab bar'],
    description: 'Switchable content panels in the same space. WAI-ARIA compliant, keyboard navigable.',
    popular: true,
  },
  {
    id: 'breadcrumb',
    name: 'Breadcrumb',
    category: 'Navigation',
    status: 'complete',
    route: '/ui-library/breadcrumb',
    aliases: ['breadcrumbs', 'trail', 'path'],
    description: 'Trail of links showing the current page\'s position in the hierarchy. Last item is not a link.',
  },
  {
    id: 'pagination',
    name: 'Pagination',
    category: 'Navigation',
    status: 'complete',
    route: '/ui-library/pagination',
    aliases: ['pages', 'pager', 'page navigation'],
    description: 'Previous, next, and numbered page controls. Pass current page and total pages.',
  },
  {
    id: 'menu',
    name: 'Menu',
    category: 'Navigation',
    status: 'complete',
    route: '/ui-library/menu',
    aliases: ['context menu', 'action menu', 'dropdown menu'],
    description: 'Contextual dropdown of actions. Supports icons, destructive items, and disabled state.',
  },
  {
    id: 'status-actions',
    name: 'Status Actions',
    category: 'Navigation',
    status: 'complete',
    route: '/ui-library/status-actions',
    aliases: ['statusMenuItems', 'lifecycle actions', 'entity status'],
    description: 'Utility that returns the correct set of transition actions for a given entity lifecycle state.',
  },
  {
    id: 'sidebar',
    name: 'Sidebar',
    category: 'Navigation',
    status: 'complete',
    route: '/ui-library/sidebar',
    aliases: ['nav', 'side nav', 'drawer nav'],
    description: 'Vertical navigation panel with collapsible groups, active state, icons, and badges.',
  },
  {
    id: 'dropdown',
    name: 'Dropdown',
    category: 'Navigation',
    status: 'complete',
    route: '/ui-library/dropdown',
    aliases: ['popdown', 'flyout'],
    description: 'Trigger that opens a floating panel with arbitrary content. Use Menu inside for action lists.',
  },
  {
    id: 'stepper',
    name: 'Stepper',
    category: 'Navigation',
    status: 'complete',
    route: '/ui-library/stepper',
    aliases: ['steps', 'wizard steps', 'progress steps'],
    description: 'Horizontal step progress indicator for multi-step flows. Shows complete, active, and upcoming steps.',
  },

  // ── Overlay ────────────────────────────────────────────────────────────
  {
    id: 'modal',
    name: 'Modal',
    category: 'Overlay',
    status: 'complete',
    route: '/ui-library/modal',
    aliases: ['dialog', 'lightbox', 'popup'],
    description: 'Focus-trapped overlay for forms and confirmations. Handles Escape, outside click, scroll lock, and focus restore.',
    popular: true,
  },
  {
    id: 'confirm-action',
    name: 'ConfirmAction',
    category: 'Overlay',
    status: 'complete',
    route: '/ui-library/confirm-action',
    aliases: ['confirm-action', 'destructive confirmation', 'inline confirm'],
    description: 'Wraps any trigger with an inline confirm/cancel step. No modal needed.',
  },
  {
    id: 'confirm-dialog',
    name: 'ConfirmDialog',
    category: 'Overlay',
    status: 'complete',
    route: '/ui-library/confirm-dialog',
    aliases: ['confirm dialog', 'delete dialog', 'destructive dialog', 'confirmation modal'],
    description: 'Dialog that asks for confirmation before a destructive action. Danger and primary tones.',
  },
  {
    id: 'drawer',
    name: 'Drawer',
    category: 'Overlay',
    status: 'complete',
    route: '/ui-library/drawer',
    aliases: ['side sheet', 'slide over', 'panel', 'bottom sheet'],
    description: 'Panel that slides in from any screen edge. Right placement is default.',
  },
  {
    id: 'dialog',
    name: 'Dialog',
    category: 'Overlay',
    status: 'complete',
    route: '/ui-library/dialog',
    aliases: ['modal dialog', 'alert dialog', 'accessible dialog'],
    description: 'Low-level dialog primitive with full compositional control. Use Modal for most cases.',
  },
  {
    id: 'popover',
    name: 'Popover',
    category: 'Overlay',
    status: 'complete',
    route: '/ui-library/popover',
    aliases: ['popup', 'floating panel'],
    description: 'Click-triggered floating panel anchored to an element. Use for forms or multi-field pickers.',
  },
  {
    id: 'tooltip',
    name: 'Tooltip',
    category: 'Overlay',
    status: 'complete',
    route: '/ui-library/tooltip',
    aliases: ['hint', 'title', 'tip'],
    description: 'Short text label shown on hover or focus. Text-only — no interactive content inside.',
  },
  {
    id: 'command-palette',
    name: 'Command Palette',
    category: 'Overlay',
    status: 'complete',
    route: '/ui-library/command-palette',
    aliases: ['command', 'spotlight', 'cmd+k'],
    description: 'Full-screen search and command overlay. Type to filter, arrow keys to navigate.',
  },
  {
    id: 'accordion',
    name: 'Accordion',
    category: 'Layout',
    status: 'complete',
    route: '/ui-library/accordion',
    aliases: ['collapsible', 'disclosure', 'expand collapse', 'expandable section'],
    description: 'Expandable/collapsible sections. Single-open or multi-open mode.',
  },

  // ── Layout ─────────────────────────────────────────────────────────────
  {
    id: 'container',
    name: 'Container',
    category: 'Layout',
    status: 'complete',
    route: '/ui-library/layout-patterns',
    aliases: ['wrapper', 'page container', 'max width', 'stack', 'grid', 'layout'],
    description: 'Page-level layout patterns — max-width containers, spacing stacks, and responsive grids.',
  },
  {
    id: 'stack',
    name: 'Stack',
    category: 'Layout',
    status: 'complete',
    route: '/ui-library/layout-patterns#stack',
    aliases: ['vstack', 'hstack', 'flex stack', 'space-y', 'vertical spacing'],
    description: 'Vertical and horizontal spacing conventions using space-y-* and flex gap.',
  },
  {
    id: 'grid',
    name: 'Grid',
    category: 'Layout',
    status: 'complete',
    route: '/ui-library/layout-patterns#grid',
    aliases: ['css grid', 'responsive grid', 'columns', 'grid-cols'],
    description: 'CSS Grid patterns for responsive multi-column layouts including the standard form grid.',
  },
  {
    id: 'toolbar',
    name: 'Toolbar',
    category: 'Layout',
    status: 'complete',
    route: '/ui-library/toolbar',
    aliases: ['action bar', 'button bar', 'filter bar', 'PersonnelToolbar'],
    description: 'Horizontal bar with a left slot for filters and a right slot for search or actions.',
  },
  {
    id: 'section',
    name: 'Section',
    category: 'Layout',
    status: 'complete',
    route: '/ui-library/section',
    aliases: ['content section', 'block'],
    description: 'Titled content block with consistent padding and heading. Lighter than a full Card.',
  },
  {
    id: 'divider',
    name: 'Divider',
    category: 'Layout',
    status: 'complete',
    route: '/ui-library/divider',
    aliases: ['separator', 'rule', 'hr'],
    description: 'Horizontal or vertical rule that visually separates sections.',
  },
  {
    id: 'page-header',
    name: 'Page Header',
    category: 'Layout',
    status: 'complete',
    route: '/ui-library/page-header',
    aliases: ['page title', 'page heading'],
    description: 'Page title area with icon, title, subtitle, and an actions slot.',
  },
  {
    id: 'wizard-layout',
    name: 'Wizard Layout',
    category: 'Layout',
    status: 'complete',
    route: '/ui-library/wizard-layout',
    aliases: ['wizard', 'multi-step layout', 'onboarding layout'],
    description: 'Full-page layout for multi-step flows. Sidebar step list, scrollable content, fixed action footer.',
  },
  {
    id: 'panel',
    name: 'Panel',
    category: 'Layout',
    status: 'complete',
    route: '/ui-library/panel',
    aliases: ['panel', 'two panel', 'catalog detail', 'lookup table', 'master detail', 'settings panel'],
    description: 'White card with a titled header. Composes into the two-panel master/detail layout.',
  },
  {
    id: 'banner',
    name: 'Banner',
    category: 'Layout',
    status: 'complete',
    route: '/ui-library/banner',
    aliases: ['page banner', 'header banner', 'navy banner', 'form banner', 'wizard banner'],
    description: 'Dark header surface for list and form pages. Variants: basic, with actions, with progress, with steps.',
  },
  {
    id: 'page-sample',
    name: 'Page',
    category: 'Layout',
    status: 'complete',
    route: '/ui-library/page-sample',
    aliases: ['page sample', 'list page', 'directory page', 'hris page', 'employee directory', 'data page'],
    description: 'Full list page layout — app shell with sidebar, stat row, toolbar, and sortable table.',
  },
  {
    id: 'form-sample',
    name: 'Form',
    category: 'Layout',
    status: 'complete',
    route: '/ui-library/form-sample',
    aliases: ['form sample', 'form layout', 'hris form', 'employee form', 'tabbed form', 'multi-section form'],
    description: 'Full form layout — tabbed sections, two-column field grid, and a sticky action footer.',
  },

  // ── Data Display ───────────────────────────────────────────────────────
  {
    id: 'heatmap',
    name: 'Heatmap',
    category: 'Data Display',
    status: 'complete',
    route: '/ui-library/heatmap',
    aliases: ['heat map', 'calendar heatmap', 'activity grid', 'attendance heatmap', 'contribution graph'],
    description: 'Calendar grid that visualises daily activity intensity with colour intensity.',
  },
  {
    id: 'table',
    name: 'Table',
    category: 'Data Display',
    status: 'complete',
    route: '/ui-library/table',
    aliases: ['data table', 'grid', 'datagrid'],
    description: 'Data table with sortable columns, row actions, and empty state. Scrolls horizontally on mobile.',
    popular: true,
  },
  {
    id: 'tree-view',
    name: 'Tree View',
    category: 'Data Display',
    status: 'complete',
    route: '/ui-library/tree-view',
    aliases: ['tree', 'treeview', 'hierarchy'],
    description: 'Expandable tree for hierarchical data — org units, file trees, categories.',
  },
  {
    id: 'calendar',
    name: 'Calendar',
    category: 'Data Display',
    status: 'complete',
    route: '/ui-library/calendar',
    aliases: ['schedule', 'date grid'],
    description: 'Standalone month-view calendar for browsing dates. Full keyboard navigation.',
  },
  {
    id: 'charts',
    name: 'Charts',
    category: 'Data Display',
    status: 'complete',
    route: '/ui-library/charts',
    aliases: ['chart', 'graph', 'visualization', 'bar chart', 'line chart', 'area chart', 'bar list', 'trend chart', 'ranked bars', 'horizontal bar', 'gradient chart', 'dual series', 'threshold line', 'annotated chart'],
    description: 'Four SVG chart primitives: BarChart, LineChart, AreaChart (gradient fill, annotations, threshold, multi-series), and BarList (ranked horizontal bars with CSS stagger).',
  },
  {
    id: 'activity-feed',
    name: 'Activity Feed',
    category: 'Data Display',
    status: 'complete',
    route: '/ui-library/activity-feed',
    aliases: ['feed', 'events', 'audit log'],
    description: 'Vertical feed of timestamped events showing who did what and when.',
  },
  {
    id: 'kanban',
    name: 'Kanban',
    category: 'Data Display',
    status: 'complete',
    route: '/ui-library/kanban',
    aliases: ['board', 'kanban board', 'columns'],
    description: 'Column-based board for visualising workflow stages. Cards are your content.',
  },
  {
    id: 'column-manager',
    name: 'ColumnManager',
    category: 'Data Display',
    status: 'complete',
    route: '/ui-library/column-manager',
    aliases: ['column visibility', 'column toggle', 'table columns', 'show hide columns', 'column order', 'column reorder'],
    description: 'Dropdown panel for showing/hiding and reordering table columns. Caller owns state. Ships with applyColumnOrder() utility.',
  },

  // ── Enterprise ─────────────────────────────────────────────────────────
  {
    id: 'employee-schedule',
    name: 'Employee Schedule',
    category: 'Enterprise',
    status: 'complete',
    route: '/ui-library/employee-schedule',
    aliases: ['schedule matrix', 'wfh schedule', 'department schedule', 'work status grid', 'employee schedule settings'],
    description: 'Department-grouped schedule matrix for managing daily work status per employee.',
  },
  {
    id: 'employee-card',
    name: 'Employee Card',
    category: 'Enterprise',
    status: 'complete',
    route: '/ui-library/employee-card',
    aliases: ['staff card', 'person card'],
    description: 'Compact identity card showing avatar, name, role, status, and optional actions.',
  },
  {
    id: 'approval-timeline',
    name: 'Approval Timeline',
    category: 'Enterprise',
    status: 'complete',
    route: '/ui-library/approval-timeline',
    aliases: ['approval trail', 'approval chain', 'approval history'],
    description: 'Vertical approval chain showing each approver\'s action, status, and timestamp.',
  },
  {
    id: 'organization-tree',
    name: 'Organization Tree',
    category: 'Enterprise',
    status: 'complete',
    route: '/ui-library/organization-tree',
    aliases: ['org tree', 'org structure', 'company tree'],
    description: 'Collapsible organisational hierarchy tree with department and role nodes.',
  },
  {
    id: 'org-unit-tree',
    name: 'Org Unit Tree',
    category: 'Enterprise',
    status: 'complete',
    route: '/ui-library/org-unit-tree',
    aliases: ['org unit', 'division tree', 'department tree'],
    description: 'Selectable tree for picking an organisational unit — division, department, or team.',
  },
  {
    id: 'org-chart',
    name: 'Org Chart',
    category: 'Enterprise',
    status: 'complete',
    route: '/ui-library/org-chart',
    aliases: ['organisation chart', 'reporting structure', 'hierarchy chart'],
    description: 'Visual org chart showing reporting lines between people and positions.',
  },
  {
    id: 'permission-matrix',
    name: 'Permission Matrix',
    category: 'Enterprise',
    status: 'complete',
    route: '/ui-library/permission-matrix',
    aliases: ['permissions', 'role matrix', 'access matrix', 'rbac table'],
    description: 'Grid showing which roles have which permissions. Presentational — no RBAC logic included.',
  },
  {
    id: 'payroll-summary',
    name: 'Payroll Summary',
    category: 'Enterprise',
    status: 'complete',
    route: '/ui-library/payroll-summary',
    aliases: ['payroll overview', 'pay summary', 'payroll card'],
    description: 'Summary card for a payroll run — total payout, employee count, period, and status.',
  },
  {
    id: 'leave-balance',
    name: 'Leave Balance',
    category: 'Enterprise',
    status: 'complete',
    route: '/ui-library/leave-balance',
    aliases: ['leave credits', 'leave summary', 'leave remaining'],
    description: 'Leave balance display per type — days used, remaining, and visual progress bar.',
  },
  {
    id: 'approval-request',
    name: 'Approval Request',
    category: 'Enterprise',
    status: 'complete',
    route: '/ui-library/approval-request',
    aliases: ['approval', 'leave request', 'approval stepper', 'approval workflow', 'filing form', 'approval detail', 'approval list'],
    description: 'Full approval request layout — list table, stepper, two-column detail view with timeline, and filing form.',
  },
  {
    id: 'batch-processing',
    name: 'Batch Processing',
    category: 'Enterprise',
    status: 'complete',
    route: '/ui-library/batch-processing',
    aliases: ['batch', 'payslip batch', '13th month batch', 'tax annualization batch', 'timekeeping review', 'bulk process', 'payroll batch'],
    description: 'Two-step batch layout — employee selection table then a sidebar queue with workspace and approve/flag actions.',
  },
  {
    id: 'company-policy',
    name: 'Company Policy & Compliance',
    category: 'Enterprise',
    status: 'complete',
    route: '/ui-library/company-policy',
    aliases: ['policy', 'compliance', 'labor code', 'government compliance', 'separation pay', 'retirement pay', 'leave policy', 'probation', 'bir', 'sss', 'philhealth'],
    description: 'Compliance layouts — labor code reference, config fields with live compliance badges, leave policy matrix, and payroll calculators.',
  },
  {
    id: 'toggle-table',
    name: 'Toggle Table',
    category: 'Enterprise',
    status: 'complete',
    route: '/ui-library/toggle-table',
    aliases: ['toggle table', 'notification settings', 'audit log', 'permission protocol', 'switch table', 'configuration matrix', 'toggle row'],
    description: 'Configuration table where each row has inline controls. Three variants: dual toggles, single toggle with severity, accordion row.',
  },
  {
    id: 'payroll-ledger',
    name: 'Payroll Ledger',
    category: 'Enterprise',
    status: 'complete',
    route: '/ui-library/payroll-ledger',
    aliases: ['pay profile', '13th month', 'tax annualization', 'ledger', 'payroll grid', 'ytd', 'bir 1604', 'pd 851'],
    description: 'Three payroll ledger layouts — pay profile, 13th month earnings grid, and tax annualization reconciliation.',
  },
  {
    id: 'email-notifications',
    name: 'Email Notifications',
    category: 'Enterprise',
    status: 'complete',
    route: '/ui-library/email-notifications',
    aliases: ['email', 'transactional email', 'leave email', 'payslip email', 'paf email', 'account activation', 'mailer'],
    description: 'Five transactional email templates — leave approval, rejection, payslip, account access, and PAF approval.',
  },
  {
    id: 'system-notifications',
    name: 'System Notifications',
    category: 'Enterprise',
    status: 'complete',
    route: '/ui-library/system-notifications',
    aliases: ['notification', 'bell', 'in-app notification', 'notification center', 'unread badge', 'notification dropdown', 'toast notification'],
    description: 'In-app notification patterns — item, bell dropdown, notification center, toast alerts, and unread badge.',
  },
  {
    id: 'template-samples',
    name: 'Template Samples',
    category: 'Enterprise',
    status: 'complete',
    route: '/ui-library/template-samples',
    aliases: ['print template', 'document template', 'paf', 'payslip template', 'timekeeping template', 'report template'],
    description: 'Four print-ready document templates — Personnel Action Form, Timekeeping Record, Payslip, and Masterlist Report.',
  },
];

// ── Helpers ────────────────────────────────────────────────────────────────────

/** Look up multiple components by id for the RelatedComponents section */
export function getRelatedComponents(ids: string[]): ComponentEntry[] {
  return ids
    .map((id) => COMPONENT_REGISTRY.find((c) => c.id === id))
    .filter((c): c is ComponentEntry => c !== undefined);
}

/** Get all components grouped by category as a Map */
export function getComponentsByCategory(): Map<GalleryCategory, ComponentEntry[]> {
  const map = new Map<GalleryCategory, ComponentEntry[]>();
  for (const cat of GALLERY_CATEGORIES) {
    map.set(cat, COMPONENT_REGISTRY.filter((c) => c.category === cat));
  }
  return map;
}
